export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const SHOW_CART_DLG = "SHOW_CART_DLG";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const UPDATE_CART_ITEM_NUMBER = "UPDATE_CART_ITEM_NUMBER";
export const SET_CHECKEDOUT_ITEMS = "SET_CHECKEDOUT_ITEMS";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const GET_MENU_DATA ="GET_MENU_DATA";
export const CLEAR_CART ="CLEAR_CART";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";


//ADMIN**********************************

//API ADMIN .NET CORE

//LOGIN
export const LOGIN  ="LOGIN";  //LOGIN 

//GET LIST
export const GET_LISTORDER_AD  ="GET_LISTORDER_AD";  //ORDER 
export const GET_LISTORDER_CLIENT="GET_LISTORDER_CLIENT"; //ORDER CLIENT
export const GET_LISTCUSTOMER_AD  ="GET_LISTCUSTOMER_AD";  //USER 
export const GET_LISTREVIEW_AD  ="GET_LISTREVIEW_AD";  //REVIEW 
export const GET_LISTPRODUCT_AD  ="GET_LISTPRODUCT_AD";  //PRODUCT
export const GET_LISTCATEGORY_AD  ="GET_LISTCATEGORY_AD";  //CATEGORY
export const GET_LISTDISCOUNT_AD  ="GET_LISTDISCOUNT_AD";  //DISCOUNT
export const GET_LISTINVOIE_AD  ="GET_LISTINVOIE_AD";  //INVOICE
export const GET_LISTPRODUCER_AD = "GET_LISTPRODUCER_AD";  //NSX
export const GET_LISTPROVIDER_AD = "GET_LISTPROVIDER_AD"; //NCC
export const GET_LISTTYPEPRODUCT_AD= "GET_LISTTYPEPRODUCT_AD";  //LSP
export const GET_LISTTYPE_USER= "GET_LISTTYPE_USER";  //LND
export const GET_LISTNEWPRODUCT= "GET_LISTNEWPRODUCT"; // NEW PRODUCT
export const GET_LISTPRODUCTBYTYPE= "GET_LISTPRODUCTBYTYPE"; //PRODUCT BY TYPE
export const GET_LISTDISCOUNTPRODUCT ="GET_LISTDISCOUNTPRODUCT";
export const GET_LISTCOMMENT="GET_LISTCOMMENT";
export const STATISTIC_AD = "STATISTIC_AD"; //GET DOANH THU BAN HANG
export const GETORDERYEAR="GETORDERYEAR" ; //LAY DOANH SO BAN RA THEO NAM
export const GETINVOICEYEAR="GETINVOICEYEAR" ; //LAY DOANH SO BAN RA THEO NAM

//GET DETAIL
export const GET_DETAILORDER_AD = "GET_DETAILORDER_AD";  //ORDER 
export const GET_DETAILPRODUCT_AD = "GET_DETAILPRODUCT_AD"; //PRODUCT ADMIN
export const GET_DETAILREVIEW_AD= "GET_DETAILREVIEW_AD"; //REVIEW
export const GET_DETAILDISCOUNT_AD = "GET_DETAILDISCOUNT_AD"; //DISCOUNT
export const GET_DETAILUSER = "GET_DETAILUSER"; //DISCOUNT
export const GET_DETAILPRODUCT = "GET_DETAILPRODUCT"; //PRODUCT CLIENT
export const GET_DETAILINVOICE_AD= "GET_DETAILINVOICE_AD"; //INVOICE


//UPDATE
export const UPDATEPRODUCT_AD = "UPDATEPRODUCT_AD" ; //PRODUCT
export const UPDATE_USER = "UPDATE_USER" ;  //USER
export const UPDATEORDER_AD= "UPDATEORDER_AD"; //ORDER
export const UPDATEORDERSTATUS_AD= "UPDATEORDERSTATUS_AD"; // ORDER STATUS
export const UPDATEDISCOUNT_AD="UPDATEDISCOUNT_AD";
//DELETE
export const DELETE_PRODUCT="DELETEPRODUCT";  //PRODUCT
export const DELETE_USER="DELETE_USER";       //USER
export const DELETE_DISCOUNT="DELETE_DISCOUNT"; //DISCOUNT
export const DELETE_REVIEW= "DELETE_REVIEW"; //REVIEW
export const DELETE_ORDER= "DELETE_ORDER"; //ORDER 
export const DELETE_INVOICE= " DELETE_INVOICE";//INVOICE
export const DELETE_REPLYREVIEW="DELETE_REPLYREVIEW"; //REPLY

//ADD
export const ADD_PRODUCT="ADD_PRODUCT" ; //PRODUCT
export const ADD_USER ="ADD_USER";    //USER
export const ADD_INVOICE="ADD_INVOICE"; //INVOICE
export const ADD_ORDER="ADD_ORDER"; // ORDER
export const ADD_DISCOUNT="ADD_DISCOUNT" //DISCOUNT
export const  ADD_COMMENT="ADD_COMMENT"; //COMMENT
export const ADD_REPLY_AD="ADD_REPLY_AD"; //REPLY COMMENT
export const UPLOADIMAGE_AD="UPLOADIMAGE_AD"; //UPLOADIMAGE




